### ISSUE TITLE
Be more robust when shift() fn is missing

### ISSUE THREAD

**Issue by binarykitchen** [totherik/caller#4]
On some older browsers shift() is not implemented. Would make it more robust there at stack.shift()

**Comment by totherik** [comment]
Back in 2013 this was originally authored to target node.js and specifically V8 (https://github.com/v8/v8/wiki/Stack-Trace-API) so I don't expect it will work without structured stack traces (e.g. not meant to work with strings). Due to that, from what I can tell he compatibility story as far as browsers are concerned most likely runs deeper than `shift()`.

That said, I don't currently have time to pursue browser compatibility but I'm always willing to accept contributions.
